pre-commit:
  commands:
    fmt:
      run: TERM=dumb just fmt
      stage_fixed: true
    lint-backend:
      run: just lint-backend
      glob:
        - "**/*.go"
        - "go.mod"
        - "go.sum"
    lint-frontend:
      run: just lint-frontend
      glob:
        - "frontend/src/**/*.{ts,svelte}"
        - "frontend/package.json"
        - "frontend/pnpm-lock.yaml"
