[server]
# address to listen on, overridable via LISTEN env var
listen = ':8080'
# reject requests not arriving via Cloudflare
# require_cloudflare = false

[log]
# debug, info, warn, error
level = 'info'
# text or json
format = 'text'

# [metrics]
# address to expose Prometheus metrics on
# listen = ':9091'

[cache]
# Redis URL, overridable via REDIS_URL env var, omit to use in-memory cache
# redis_url = 'redis://localhost:6379'

# comment out keys to disable expiration
[cache.ttl]
# word-level results
word = '0s'
# line-level results
line = '720h0m0s'
# unsynced results
none = '168h0m0s'
# provider not-found results
miss = '24h0m0s'

[ratelimit]
# max requests per window per IP
limit = 45
# rate limit time window
window = '1h0m0s'

# [proxies]
# [proxies.mypool]
# urls = ['socks5://user:pass@proxy1.example.com:1080']

[provider]
# timeout for provider requests
timeout = '5s'

[providers]
[providers.genius]
enable = true
# proxy = 'mypool'

[providers.kugou]
enable = true

[providers.lrclib]
enable = true
# which instance to use
# base_url = 'https://lrclib.net'

[providers.musixmatch]
enable = true
# how many tokens to use in rotation
# pool_size = 5

[providers.netease]
enable = true

[providers.ytmusic]
enable = true
