services:
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

  api:
    image: ghcr.io/f1nniboy/lrcmux-api:latest
    ports:
      - "8080:8080"
    volumes:
      - ./config.toml:/etc/lrcmux/config.toml:ro,z
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis

  frontend:
    image: ghcr.io/f1nniboy/lrcmux-frontend:latest
    ports:
      - "3000:3000"
    environment:
      PUBLIC_API_URL: http://localhost:8080
      API_URL: http://api:8080
    depends_on:
      - api

volumes:
  redis_data:
