app = 'lrcmux-api'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'
  build-target = 'api'

[[files]]
  guest_path = '/etc/lrcmux/config.toml'
  secret_name = 'APP_CONFIG'

[env]
  LISTEN = '0.0.0.0:8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 1000
    soft_limit = 800

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '5s'
    method = 'GET'
    path = '/health'

[metrics]
  port = 9091
  path = '/metrics'

[[vm]]
  memory = '256mb'
  cpus = 1
