[formatter.go]
command = "gofmt"
includes = ["*.go"]

[formatter.prettier]
command = "frontend/node_modules/.bin/prettier"
includes = ["*.{js,ts,svelte,css,json,yaml,yml}"]
options = ["--plugin", "./frontend/node_modules/prettier-plugin-svelte/plugin.js", "--write"]
